name: Build Mesa Turnip Debian Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up the build environment
      - name: Set up build environment
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y software-properties-common
          sudo apt-get build-dep -y mesa
          sudo apt-get install -y pkg-config make cmake \
                                  g++-arm-linux-gnueabihf g++-aarch64-linux-gnu \
                                  gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
          sudo apt-get install -y zlib1g-dev libexpat1-dev libdrm-dev libx11-dev libx11-xcb-dev \
                                  libxext-dev libxdamage-dev libxcb-glx0-dev libxcb-dri2-0-dev libxcb-dri3-dev \
                                  libxcb-shm0-dev libxcb-present-dev libxshmfence-dev libxxf86vm-dev libxrandr-dev \
                                  libwayland-dev wayland-protocols libwayland-egl-backend-dev libssl-dev

      # Copy drm headers
      - name: Copy DRM headers
        run: |
          sudo cp /usr/include/libdrm/drm.h /usr/include/libdrm/drm_mode.h /usr/include/

      # Set up build directories and download Mesa source
      - name: Download Mesa source
        run: |
          BUILD_PREFIX=~/Desktop
          MESA_PREFIX=${BUILD_PREFIX}/mesa-turnip-feature-a7xx-basic-support
          mkdir -p ${BUILD_PREFIX}
          wget --continue --directory-prefix ${BUILD_PREFIX} \
            https://gitlab.freedesktop.org/Danil/mesa/-/archive/turnip/feature/a7xx-basic-support/mesa-turnip-feature-a7xx-basic-support.tar.gz
          tar -xf ${BUILD_PREFIX}/*.tar.gz --directory ${BUILD_PREFIX}

      # Configure Mesa build
      - name: Configure Mesa build
        run: |
          BUILD_PREFIX=~/Desktop
          MESA_PREFIX=${BUILD_PREFIX}/mesa-turnip-feature-a7xx-basic-support
          MESA_VER=$(cat ${MESA_PREFIX}/VERSION)
          DATE=$(date +"%F" | sed 's/-//g')
          MESA_64=${BUILD_PREFIX}/mesa-vulkan-kgsl_${MESA_VER}-${DATE}_arm64
          echo "[binaries]
          c = 'arm-linux-gnueabihf-gcc'
          cpp = 'arm-linux-gnueabihf-g++'
          ar = 'arm-linux-gnueabihf-ar'
          strip = 'arm-linux-gnueabihf-strip'
          pkgconfig = 'arm-linux-gnueabihf-pkg-config'

          [host_machine]
          system = 'linux'
          cpu_family = 'arm'
          cpu = 'aarch64'
          endian = 'little'" > ${MESA_PREFIX}/arm.txt

      # Download and apply the patch
      - name: Download and apply DRI patch
        run: |
          BUILD_PREFIX=~/Desktop
          MESA_PREFIX=${BUILD_PREFIX}/mesa-turnip-feature-a7xx-basic-support
          wget -O dri.zip https://github.com/xDoge26/proot-setup/files/12564533/dri.zip
          unzip dri.zip -d ${MESA_PREFIX}
          cd ${MESA_PREFIX}
          patch -p1 -i wsi-termux-x11-v3.patch
          cp wsi_common_x11.c src/vulkan/wsi/wsi_common_x11.c

      # Build Mesa Turnip
      - name: Build Mesa Turnip
        run: |
          BUILD_PREFIX=~/Desktop
          MESA_PREFIX=${BUILD_PREFIX}/mesa-turnip-feature-a7xx-basic-support
          MESA_VER=$(cat ${MESA_PREFIX}/VERSION)
          DATE=$(date +"%F" | sed 's/-//g')
          MESA_64=${BUILD_PREFIX}/mesa-vulkan-kgsl_${MESA_VER}-${DATE}_arm64
          cd ${MESA_PREFIX}
          sudo meson setup build64/ --prefix /usr --libdir lib/aarch64-linux-gnu/ \
            -D platforms=x11,wayland -D gallium-drivers=freedreno \
            -D vulkan-drivers=freedreno -D freedreno-kmds=msm,kgsl \
            -D dri3=enabled -D buildtype=release -D glx=disabled \
            -D egl=disabled -D gles1=disabled -D gles2=disabled \
            -D gallium-xa=disabled -D opengl=false -D shared-glapi=false \
            -D b_lto=true -D b_ndebug=true -D cpp_rtti=false -D gbm=disabled \
            -D llvm=disabled -D shared-llvm=disabled -D xmlconfig=disabled
          sudo meson compile -C build64/
          sudo meson install -C build64/ --destdir ${MESA_64}

      # Create Debian package
      - name: Create Debian package
        run: |
          BUILD_PREFIX=~/Desktop
          MESA_VER=$(cat ${BUILD_PREFIX}/mesa-turnip-feature-a7xx-basic-support/VERSION)
          DATE=$(date +"%F" | sed 's/-//g')
          MESA_64=${BUILD_PREFIX}/mesa-vulkan-kgsl_${MESA_VER}-${DATE}_arm64
          cd ${BUILD_PREFIX}
          # Create DEBIAN directory and control file with sudo
          sudo mkdir -p ${MESA_64}/DEBIAN
          sudo bash -c "echo 'Package: mesa-vulkan-drivers
Version: ${MESA_VER}-${DATE}
Architecture: arm64
Maintainer: playbyan1453
Description: Mesa Vulkan drivers with Turnip support for Termux's Proot environment
Depends: libc6 (>= 2.17), libdrm2 (>= 2.4.91), libwayland-client0 (>= 1.9.0), libx11-6, libxcb1
' > ${MESA_64}/DEBIAN/control"
          # Build the .deb package with sudo
          sudo dpkg-deb --build --root-owner-group ${MESA_64}

      # Upload the artifact
      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-deb
          path: ~/Desktop/mesa-vulkan-kgsl_*.deb
          retention-days: 7
