# Based of this reply from hansm629:
# https://github.com/xDoge26/proot-setup/issues/26#issuecomment-1712404849
name: Build Mesa with Turnip driver for ARM64 and ARMHF

on:
  # push:
    # branches:
      # - main
  # pull_request:
    # branches:
      # - main
  workflow_dispatch:
    inputs:
      mesa-version:
        description: 'Mesa version to build (e.g., 24.0.2)'
        required: false
        default: '24.0.2'

jobs:
  build-turnip:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        # git wget mesa-utils vulkan-tools \
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
          sudo apt update
          sudo apt build-dep mesa
          sudo apt install -y pkg-config make cmake \
                              g++-arm-linux-gnueabihf g++-aarch64-linux-gnu \
                              gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
          sudo apt install -y zlib1g-dev libexpat1-dev libdrm-dev libx11-dev libx11-xcb-dev \
                              libxext-dev libxdamage-dev libxcb-glx0-dev libxcb-dri2-0-dev libxcb-dri3-dev \
                              libxcb-shm0-dev libxcb-present-dev libxshmfence-dev libxxf86vm-dev libxrandr-dev \
                              libwayland-dev wayland-protocols libwayland-egl-backend-dev libssl-dev
          sudo cp /usr/include/libdrm/drm.h /usr/include/libdrm/drm_mode.h /usr/include/

      - name: Build Mesa with Turnip
        env:
          MESA_VERSION: ${{ github.event.inputs.mesa-version || '24.0.2' }}
        run: |
          chmod +x build_turnip.sh
          echo "Building Mesa version: $MESA_VERSION"
          bash build_turnip.sh "$MESA_VERSION"

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ github.event.inputs.mesa-version || '24.0.2' }}-arm64
          path: ~/mesa-cross-build/mesa-${{ github.event.inputs.mesa-version || '24.0.2' }}-aarch64.tar.gz

      - name: Upload ARMHF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ github.event.inputs.mesa-version || '24.0.2' }}-armhf
          path: ~/mesa-cross-build/mesa-${{ github.event.inputs.mesa-version || '24.0.2' }}-armhf.tar.gz
