name: Build Turnip Mesa for ARM64 and ARMHF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-turnip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Add deb-src lines by duplicating deb lines and replacing 'deb' with 'deb-src'
          sudo sed -E 's/^deb (.*)$/deb \1\ndeb-src \1/' /etc/apt/sources.list > /tmp/sources.list
          sudo mv /tmp/sources.list /etc/apt/sources.list
          # Update package lists with source repositories
          sudo apt-get update -y
          # Install Mesa build dependencies
          sudo apt-get build-dep mesa -y
          # Install additional tools for cross-compilation and build
          sudo apt-get install -y git meson ninja-build cmake python3 python3-pip \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            glslang-tools
          pip3 install mako

      - name: Make Build Script Executable
        run: chmod +x build_turnip.sh

      - name: Build Mesa with Turnip
        run: ./build_turnip.sh

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-arm64
          path: ~/mesa-cross-build/mesa-24.0.2-aarch64.tar.gz

      - name: Upload ARMHF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-armhf
          path: ~/mesa-cross-build/mesa-24.0.2-armhf.tar.gz
