name: Build ARMHF and ARM64 Debian Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [armhf, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-make quilt

    - name: Build Debian package for ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" == "armhf" ]; then
          docker run --rm -v $(pwd):/src -w /src multiarch/qemu-user-static --reset -p yes
          dpkg-buildpackage -us -uc -aarmhf
        elif [ "${{ matrix.arch }}" == "arm64" ]; then
          docker run --rm -v $(pwd):/src -w /src multiarch/qemu-user-static --reset -p yes
          dpkg-buildpackage -us -uc -aarm64
        fi

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: deb-package-${{ matrix.arch }}
        path: ../proot-setup_*.deb
