name: Build Mesa Vulkan-KGSL (ARM)

on: [workflow_dispatch, push]

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, armhf]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        build-essential meson ninja-build pkg-config \
        crossbuild-essential-arm64 crossbuild-essential-armhf \
        libdrm-dev:arm64 libdrm-dev:armhf

    - name: Clone Mesa
      run: |
        git clone https://gitlab.freedesktop.org/mesa/mesa -b 24.0.3
        cd mesa
        # Apply patches here

    - name: Setup cross-compile
      working-directory: ./mesa
      run: |
        echo "[binaries]
        c = '${CC}'
        cpp = '${CXX}'
        ar = '${AR}'
        strip = 'strip'
        [host_machine]
        system = 'linux'
        cpu_family = '${CPU_FAMILY}'
        cpu = '${CPU}'
        endian = 'little'" > crossfile.ini

    - name: Configure & Build
      working-directory: ./mesa
      env:
        CC: ${{ matrix.arch == 'arm64' && 'aarch64-linux-gnu-gcc' || 'arm-linux-gnueabihf-gcc' }}
        CXX: ${{ matrix.arch == 'arm64' && 'aarch64-linux-gnu-g++' || 'arm-linux-gnueabihf-g++' }}
        AR: ${{ matrix.arch == 'arm64' && 'aarch64-linux-gnu-ar' || 'arm-linux-gnueabihf-ar' }}
        CPU_FAMILY: ${{ matrix.arch == 'arm64' && 'aarch64' || 'arm' }}
        CPU: ${{ matrix.arch }}
      run: |
        meson build-${{ matrix.arch }} \
          --cross-file crossfile.ini \
          -Dvulkan-drivers=kgsl \
          -Dplatforms= -Dglx=disabled
        ninja -C build-${{ matrix.arch }}

    - name: Package
      run: |
        mkdir -p artifacts
        cp mesa/build-${{ matrix.arch }}/src/vulkan/driver/*kgsl* artifacts/
        tar czvf mesa-vulkan-kgsl-${{ matrix.arch }}.tar.gz artifacts/

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mesa-kgsl-${{ matrix.arch }}
        path: mesa-vulkan-kgsl-${{ matrix.arch }}.tar.gz
