# Based of this reply from hansm629:
# https://github.com/xDoge26/proot-setup/issues/26#issuecomment-1712404849
name: Build Mesa with Turnip driver for ARM64 and ARMHF

on:
  # push:
    # branches:
      # - main
  # pull_request:
    # branches:
      # - main
  workflow_dispatch:
    inputs:
      mesa-version:
        description: 'Mesa version to build (e.g., 24.0.2)'
        required: false
        default: '24.0.2'

jobs:
  build-turnip:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
          sudo apt update
          sudo apt upgrade -y
          sudo apt build-dep mesa
          sudo apt install -y make cmake git wget vulkan-tools mesa-utils g++-arm-linux-gnueabihf g++-aarch64-linux-gnu
          sudo apt install -y zlib1g-dev:arm64 libexpat1-dev:arm64 libdrm-dev:arm64 libx11-dev:arm64 libx11-xcb-dev:arm64 \
                              libxext-dev:arm64 libxdamage-dev:arm64 libxcb-glx0-dev:arm64 libxcb-dri2-0-dev:arm64 libxcb-dri3-dev:arm64 \
                              libxcb-shm0-dev:arm64 libxcb-present-dev:arm64 libxshmfence-dev:arm64 libxxf86vm-dev:arm64 libxrandr-dev:arm64 \
                              libwayland-dev:arm64 wayland-protocols:arm64 libwayland-egl-backend-dev:arm64
          sudo cp /usr/include/libdrm/drm.h /usr/include/libdrm/drm_mode.h /usr/include/

      - name: Build Mesa with Turnip
        env:
          MESA_VERSION: ${{ github.event.inputs.mesa-version || '24.0.2' }}
        run: |
          chmod +x build_turnip.sh
          echo "Building Mesa version: $MESA_VERSION"
          bash build_turnip.sh "$MESA_VERSION"

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ github.event.inputs.mesa-version || '24.0.2' }}-arm64
          path: ~/mesa-cross-build/mesa-${{ github.event.inputs.mesa-version || '24.0.2' }}-aarch64.tar.gz

      - name: Upload ARMHF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ github.event.inputs.mesa-version || '24.0.2' }}-armhf
          path: ~/mesa-cross-build/mesa-${{ github.event.inputs.mesa-version || '24.0.2' }}-armhf.tar.gz
