name: Build Mesa with Turnip driver for ARM64 and ARMHF

on:
    # push:
    #     branches: [main]
    # pull_request:
    #     branches: [main]
    workflow_dispatch:
        inputs:
            mesa-version:
                description: 'Mesa version to build (e.g., 24.1.0)'
                required: false
                default: '24.1.0'
            use-patches:
                description: 'Will be using paches from /patches folder'
                required: false
                default: false

env:
    MESA_VERSION: ${{ github.event.inputs.mesa-version || '24.1.0' }}
    USE_PATCHES: ${{ github.event.inputs.use-patches || 'false' }}

jobs:
    build-turnip:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Cross-Compile Support (ARM64)
              uses: cyberjunk/gha-ubuntu-cross@v5
              with:
                  arch: arm64

            - name: Install Cross-Compile Support (ARMHF)
              uses: cyberjunk/gha-ubuntu-cross@v5
              with:
                  arch: armhf

            - name: Set up build environment
              run: |
                    sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
                    sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
                    sudo apt-get update -y
                    sudo apt-get install -y \
                        pkg-config make cmake ninja-build software-properties-common wget patch \
                        gcc-aarch64-linux-gnu g++-aarch64-linux-gnu pkg-config:arm64 \
                        gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf pkg-config:armhf 
                    sudo apt-get build-dep -a arm64 mesa
                    sudo apt-get build-dep -a armhf mesa
                    sudo cp /usr/include/libdrm/drm.h /usr/include/libdrm/drm_mode.h /usr/include/

            - name: Build Mesa with Turnip
              run: |
                    echo "Building Mesa version: $MESA_VERSION"
                    bash build_turnip.sh "$MESA_VERSION"

            - name: Upload ARM64 Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: mesa-turnip-${{ env.MESA_VERSION }}-arm64
                  path: ~/mesa-build/mesa-vulkan-kgsl_${{ env.MESA_VERSION }}-*-arm64.*

            - name: Upload ARMHF Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: mesa-turnip-${{ env.MESA_VERSION }}-armhf
                  path: ~/mesa-build/mesa-vulkan-kgsl_${{ env.MESA_VERSION }}-*-armhf.*
