name: Build Turnip Mesa for ARM64 and ARMHF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mesa-version:
        description: 'Mesa version to build (e.g., 24.0.2)'
        required: false
        default: '24.0.2'

jobs:
  build-turnip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
          sudo apt update
          sudo apt build-dep mesa
          sudo apt install make cmake g++-arm-linux-gnueabihf g++-aarch64-linux-gnu
          sudo apt install zlib1g-dev:armhf libexpat1-dev:armhf libdrm-dev:armhf libx11-dev:armhf libx11-xcb-dev:armhf libxext-dev:armhf libxdamage-dev:armhf libxcb-glx0-dev:armhf libxcb-dri2-0-dev:armhf libxcb-dri3-dev:armhf libxcb-shm0-dev:armhf libxcb-present-dev:armhf libxshmfence-dev:armhf libxxf86vm-dev:armhf libxrandr-dev:armhf libwayland-dev:armhf wayland-protocols:armhf libwayland-egl-backend-dev:armhf 
          sudo apt install zlib1g-dev:arm64 libexpat1-dev:arm64 libdrm-dev:arm64 libx11-dev:arm64 libx11-xcb-dev:arm64 libxext-dev:arm64 libxdamage-dev:arm64 libxcb-glx0-dev:arm64 libxcb-dri2-0-dev:arm64 libxcb-dri3-dev:arm64 libxcb-shm0-dev:arm64 libxcb-present-dev:arm64 libxshmfence-dev:arm64 libxxf86vm-dev:arm64 libxrandr-dev:arm64 libwayland-dev:arm64 wayland-protocols:arm64 libwayland-egl-backend-dev:arm64  
          sudo cp /usr/include/libdrm/drm.h /usr/include/libdrm/drm_mode.h /usr/include/


      - name: Build Mesa with Turnip
        env:
          MESA_VERSION: ${{ github.event.inputs.mesa-version || '24.0.2' }}
        run: |
          chmod +x build_turnip.sh
          echo "Building Mesa version: $MESA_VERSION"
          bash build_turnip.sh "$MESA_VERSION"

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ github.event.inputs.mesa-version || '24.0.2' }}-arm64
          path: ~/mesa-cross-build/mesa-${{ github.event.inputs.mesa-version || '24.0.2' }}-aarch64.tar.gz

      - name: Upload ARMHF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ github.event.inputs.mesa-version || '24.0.2' }}-armhf
          path: ~/mesa-cross-build/mesa-${{ github.event.inputs.mesa-version || '24.0.2' }}-armhf.tar.gz
