name: build-deb-packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, ARMHF, ARM64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build DEB packages
      run: |
        # Add your build commands here
        echo "Building DEB packages for ARMHF and ARM64"

    - name: Upload DEB packages
      uses: actions/upload-artifact@v2
      with:
        name: deb-packages
        path: |
          path/to/deb-packages/*.deb
