name: Build Turnip Mesa for ARM64 and ARMHF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-turnip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get build-dep mesa -y

      - name: Make Build Script Executable
        run: chmod +x build_turnip.sh

      - name: Build Mesa with Turnip
        run: ./build_turnip.sh

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-arm64
          path: ~/mesa-cross-build/mesa-24.0.2-aarch64.tar.gz

      - name: Upload ARMHF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-armhf
          path: ~/mesa-cross-build/mesa-24.0.2-armhf.tar.gz
