name: Build Mesa with Turnip driver for ARM64 and ARMHF

on:
  # push:
  #     branches: [main]
  # pull_request:
  #     branches: [main]
  workflow_dispatch:
    inputs:
      mesa-version:
        description: 'Mesa version to build (e.g., 24.3.4)'
        required: false
        default: '24.3.4'
      use-patches:
        description: 'Apply patches from /patches folder'
        required: false
        default: false

env:
  MESA_VERSION: ${{ github.event.inputs.mesa-version || '24.3.4' }}
  USE_PATCHES: ${{ github.event.inputs.use-patches || 'false' }}

jobs:
  build-turnip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure APT sources
        run: |
          sudo dpkg --add-architecture arm64
          sudo dpkg --add-architecture armhf
          CODENAME=$(lsb_release -c -s)
          sudo rm -f /etc/apt/sources.list
          sudo rm -rf /etc/apt/sources.list.d/*
          cat << EOF | sudo tee /etc/apt/sources.list
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME main restricted universe multiverse
          deb-src [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-updates main restricted universe multiverse
          deb-src [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-updates main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-security main restricted universe multiverse
          deb-src [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-security main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-backports main restricted universe multiverse
          deb-src [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-backports main restricted universe multiverse
          EOF
          cat << EOF | sudo tee /etc/apt/sources.list.d/cross-compile.list
          deb [arch=arm64,armhf] http://ports.ubuntu.com/ $CODENAME main restricted universe multiverse
          deb-src [arch=arm64,armhf] http://ports.ubuntu.com/ $CODENAME main restricted universe multiverse
          deb [arch=arm64,armhf] http://ports.ubuntu.com/ $CODENAME-updates main restricted universe multiverse
          deb-src [arch=arm64,armhf] http://ports.ubuntu.com/ $CODENAME-updates main restricted universe multiverse
          EOF
          sudo apt-get update

      - name: Set up build environment
        run: |
          sudo apt-get build-dep mesa 
          sudo apt-get install -y g++-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf
          sudo apt-get install -y pkg-config:arm64 zlib1g-dev:arm64 libexpat1-dev:arm64 libdrm-dev:arm64 libx11-dev:arm64 \
                                  libx11-xcb-dev:arm64 libxext-dev:arm64 libxdamage-dev:arm64 libxcb-glx0-dev:arm64 \
                                  libxcb-dri2-0-dev:arm64 libxcb-dri3-dev:arm64 libxcb-shm0-dev:arm64 libxcb-present-dev:arm64 \
                                  libxshmfence-dev:arm64 libxxf86vm-dev:arm64 libxrandr-dev:arm64 libglvnd-dev:arm64 \
                                  pkg-config:armhf zlib1g-dev:armhf libexpat1-dev:armhf libdrm-dev:armhf libx11-dev:armhf \
                                  libx11-xcb-dev:armhf libxext-dev:armhf libxdamage-dev:armhf libxcb-glx0-dev:armhf \
                                  libxcb-dri2-0-dev:armhf libxcb-dri3-dev:armhf libxcb-shm0-dev:armhf libxcb-present-dev:armhf \
                                  libxshmfence-dev:armhf libxxf86vm-dev:armhf libxrandr-dev:armhf libglvnd-dev:armhf

      - name: Build Mesa with Turnip
        run: |
          echo "Building Mesa version: $MESA_VERSION"
          chmod +x build_turnip.sh
          bash build_turnip.sh "$MESA_VERSION"

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ env.MESA_VERSION }}-arm64
          path: ~/mesa-build/mesa-vulkan-kgsl_${{ env.MESA_VERSION }}-*-arm64.deb

      - name: Upload ARMHF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-turnip-${{ env.MESA_VERSION }}-armhf
          path: ~/mesa-build/mesa-vulkan-kgsl_${{ env.MESA_VERSION }}-*-armhf.deb

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mesa-builds
          path: |
            ~/mesa-*/build-*
            ~/mesa-*/install-*
