name: Test Build Script

on:
    # push:
    #     branches: [main]
    # pull_request:
    #     branches: [main]
    workflow_dispatch:

env:
    MESA_VERSION: '25.0.1'

jobs:
    build-turnip:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Test Building script
              run: |
                    bash build_turnip.sh "$MESA_VERSION"
